// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MicaVisualStudio
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMVSPackageString = "1a10bdf6-6cb0-415e-8ddd-f16d897f1e4a";
        public static Guid guidMVSPackage = new Guid(guidMVSPackageString);

        public const string imageCatalogString = "ae27a6b0-e345-4288-96df-5eaf394ee369";
        public static Guid imageCatalog = new Guid(imageCatalogString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MVSMenuGroup = 0x1020;
        public const int BackdropSubMenu = 0x1100;
        public const int MaterialsSubmenuGroup = 0x1150;
        public const int MoreSubmenuGroup = 0x1200;
        public const int NoneCommandId = 0x0100;
        public const int MicaCommandId = 0x0105;
        public const int TabbedCommandId = 0x0110;
        public const int AcrylicCommandId = 0x0115;
        public const int GlassCommandId = 0x0120;
        public const int MoreCommandId = 0x0125;
        public const int settings = 0x0ACF;
    }
}
