// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MicaVisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "MicaVisualStudio.8fbea740-d2b6-47c3-a69f-ace0c4f526ac";
        public const string Name = "Mica Visual Studio";
        public const string Description = @"Enhance your Visual Studio experience with Windows materials";
        public const string Language = "en-US";
        public const string Version = "2.1.4";
        public const string Author = "Tech5G5G";
        public const string Tags = "Design, Modern, Theme, UI, Windows, Mica, Tabbed, Acrylic, Glass";
        public const bool IsPreview = false;
    }
}
